/**
 * PSXAPI_r10_00_01.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.sonusnet.www.ems.emsapi.psx.r10_00_01.intf;

public interface PSXAPI_r10_00_01 extends java.rmi.Remote {
    public com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityKey[] getNextItems(java.lang.String in0, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityKey in1, int in2, int in3) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException;
    public void bulkDelete(java.lang.String in0, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityValue in1, java.lang.String in2) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException;
    public java.lang.String listall(java.lang.String in0, java.lang.String in1, java.lang.String in2, boolean in3, boolean in4) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException;
    public void bulkUpdate(java.lang.String in0, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityValue in1, java.lang.String in2) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException;
    public java.lang.String getJobStatus(java.lang.String in0) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException;
    public com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityValue[] bulkRetrieve(java.lang.String in0, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityValue in1, int in2, int in3, java.lang.String[] in4, java.lang.String in5) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException;
    public void put(java.lang.String in0, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityValue in1) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException;
    public void put(java.lang.String in0, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityValue[] in1, boolean in2) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiBatchException;
    public void delete(java.lang.String in0, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityKey in1) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException;
    public void delete(java.lang.String in0, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityKey[] in1, boolean in2) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiBatchException;
    public void create(java.lang.String in0, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityValue in1) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException;
    public void create(java.lang.String in0, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityValue[] in1, boolean in2) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiBatchException;
    public void update(java.lang.String in0, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityKey in1, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityValue in2) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException;
    public void update(java.lang.String in0, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityKey[] in1, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityValue in2, boolean in3) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiBatchException;
    public com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityValue retrieve(java.lang.String in0, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityKey in1) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException;
    public com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityValue[] retrieve(java.lang.String in0, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityKey[] in1, boolean in2) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiBatchException;
    public int getCount(java.lang.String in0, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ManagedEntityValue in1, java.lang.String in2, java.lang.String[] in3) throws java.rmi.RemoteException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiException, com.sonusnet.www.ems.emsapi.psx.r10_00_01.model.ProvApiAuthorizationException;
}
